<?php
/**
 * @var $block \Genaker\ProductVariants\Block\ProductVariants
 */

$atr =  ['color_variants'=>'color'];
$swatchers = $block->getProductVariantSwatchesByAttribute($atr);

?>

<div class="swatch-opt-1940">
    <div class="swatch-attribute color" attribute-code="color" attribute-id="93">
        <div class="swatch-attribute-options clearfix">
            <div class="swatch-option color" option-type="1" option-id="52" option-label="Gray" option-tooltip-thumb=""
                option-tooltip-value="#8f8f8f" "="" style=" background: #8f8f8f no-repeat center; background-size:
                initial;">
            </div>
            <div class="swatch-option color" option-type="1" option-id="56" option-label="Orange"
                option-tooltip-thumb="" option-tooltip-value="#eb6703" "="" style=" background: #eb6703 no-repeat
                center; background-size: initial;">

                <div class="swatch-option color" option-type="1" option-id="60" option-label="Yellow"
                    option-tooltip-thumb="" option-tooltip-value="#ffd500" "="" style=" background: #ffd500 no-repeat
                    center; background-size: initial;">
                </div>
            </div>